### ISSUE TITLE
Safari iOS Support

### ISSUE THREAD

**Issue by vschwaberow** [markuszeller/image-stitcher#13]
Support iOS Safari - at the moment nonworking.

**Comment by markuszeller** [comment]
Is there any error message in the console?

**Comment by vschwaberow** [comment]
With iOS Safari this is - I think - not really problem-free. You have to couple XCode with it. I don't have the environment now. But I also think it has to do with the touch environment, which can't be applied here to adding visuals.

According to my fixed idea, you could implement a second strand that takes care of mobile device support.

**Comment by vschwaberow** [comment]
#14 fixes this
